#! /bin/sh

chksrc() {
    test -f modinc || return 1
    test -f stub.ac || return 1
    src=`sed -n 's/AC_CONFIG_SRCDIR(\[\(.*\)\]).*/\1/p' stub.ac`
    test -n "$src" || return 1
    test -f $src
}

if ! chksrc; then
    echo "$0: must be run from the Dico source tree root directory"
    exit 1
fi

set -e
git submodule init
git submodule update
./modinc
set +e
gnulib=gnulibinit
test -L $gnulib || ln -sf ./gnulib/build-aux/bootstrap $gnulib
./$gnulib
