\input texinfo @c -*-texinfo-*-
@smallbook
@c %**start of header
@setfilename dico.info
@settitle Dico
@c %**end of header
@setchapternewpage odd

@defcodeindex pr
@defcodeindex op
@defcodeindex kw
@defcodeindex fl

@syncodeindex fn cp
@syncodeindex vr cp
@syncodeindex ky cp
@syncodeindex pg cp
@syncodeindex tp cp
@syncodeindex op cp
@syncodeindex pr cp
@syncodeindex kw cp
@syncodeindex fl cp

@include version.texi
@include rendition.texi
@include macros.texi

@ifinfo
@dircategory Dictionary
@direntry
* dico: (dico).         A modular dictionary server.
@end direntry
@end ifinfo

@copying
Published by the Free Software Foundation,
51 Franklin Street, Fifth Floor,
Boston, MA 02110-1301 USA 

Copyright @copyright{} 2008 Sergey Poznyakoff

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover texts being ``Dico Manual'',
and with the Back-Cover Texts as in (a) below.  A copy of the license
is included in the section entitled ``GNU Free Documentation License''.

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''
@end copying

@titlepage
@title Dico
@subtitle version @value{VERSION}, @value{UPDATED}
@author Sergey Poznyakoff.
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@ifnottex
@node Top
@top Dico

This edition of the @cite{Dico Manual}, last updated @value{UPDATED},
documents @command{dico} Version @value{VERSION}.

@end ifnottex

@menu
* Preface::             
* Intro::                Introduction to Dico.
* Building::             Building the Package.
* Dictd::                The dictd daemon.
* Modules::              Dictd modules shipped with Dico.
* Interface::            How to write your own Dico module.
* Reporting Bugs::       How to Report a Bug.

Appendices

* Time and Date Formats::
* Copying This Manual::  The GNU Free Documentation License.
* Concept Index::        Index of Concepts.

@detailmenu
 --- The Detailed Node Listing ---

The @command{dictd} daemon.

* Configuration::
* Dictd Invocation::

Modules

* Outline::
* Dictorg::
* Guile::

@end detailmenu
@end menu

@node Preface
@unnumbered Preface
@UNREVISED

@node Intro
@chapter Introduction to @command{Dico}
@UNREVISED
@dfn{Dico} is a flexible modular dictionary system.  It consists of a
daemon complying with @acronym{RFC} 2229 and a set of modules for
handling various dictionary formats@footnote{Command-line and
X-based client programs will be added in the nearest future.}.  In
contrast to existing implementations of @acronym{RFC} 2229,
@command{dico} does not impose a specific dictionary format.  Instead,
it is built in a modular fashion.  The daemon itself, @command{dictd},
is responsible for protocol interaction, but knows nothing about
dictionary formats.  Whenever it needs to access a database, it calls
a @dfn{module}, which is responsible for fetching the actual data.

@node Building
@chapter Building the Package
@UNREVISED

@node Dictd
@chapter The @command{dictd} daemon.
@UNREVISED

@menu
* Configuration::
* Dictd Invocation::
@end menu

@node Configuration
@section Configuration
@UNREVISED

@node Dictd Invocation
@section Dictd Invocation
@UNREVISED

@node Modules
@chapter Modules
@UNREVISED

@menu
* Outline::
* Dictorg::
* Guile::
@end menu

@node Outline
@section The @command{outline} module.
@UNREVISED

@node Dictorg
@section The @command{dictorg} module.
@UNREVISED

@node Guile
@section The @command{guile} module.
@UNREVISED

@node Interface
@chapter Dico Module Interface
@UNREVISED

@node Reporting Bugs
@chapter How to Report a Bug
@UNREVISED

@node Time and Date Formats
@appendix Time and Date Formats
@include strftime.texi

@node Copying This Manual
@appendix GNU Free Documentation License
@include fdl.texi

@node Concept Index
@comment node-name,  next,  previous,  up
@unnumbered Concept Index

This is a general index of all issues discussed in this manual

@printindex cp

@bye




